@echo off

REM 设置Streamlit配置
set STREAMLIT_SERVER_HEADLESS=true
set STREAMLIT_SERVER_FILE_WATCHER_TYPE=none
set STREAMLIT_SERVER_ADDRESS=0.0.0.0
set STREAMLIT_SERVER_PORT=8501

REM 启动应用程序
streamlit run app.py
